spring.application.name=user-service
server.port=8082

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${RDS_USERNAME}
spring.datasource.password=${RDS_PASSWORD}
spring.datasource.url=${RDS_URL}
spring.jpa.show-sql=true

internal.api.key=${USER_SERVICE_SECRET}

# Set the specific logger for expression authorization
logging.level.org.springframework.security.access.expression.ExpressionUtils=TRACE

# Optionally, set the logger for the main security filter chain to see more detail
logging.level.org.springframework.security.web.access.intercept.AuthorizationFilter=DEBUG